"""Deterministic Mermaid data-flow diagram from the resource graph (G5/FR-8, ADR-3).

Generated by code (not the LLM) so it always renders and never hallucinates topology. Public
resources are linked from an Internet boundary node and highlighted.
"""

from __future__ import annotations


def _label(resource: dict) -> str:
    name = str(resource.get("name", "")).replace('"', "'")
    rtype = str(resource.get("type", "")).replace('"', "'")
    return f"{name}<br/>{rtype}"


def build_dfd(graph: dict) -> str:
    resources = graph.get("resources", [])
    lines = ["flowchart LR", "    internet([Internet]):::ext"]
    idmap: dict[str, str] = {}
    public_nodes: list[str] = []

    for i, res in enumerate(resources):
        nid = f"n{i}"
        idmap[res["id"]] = nid
        lines.append(f'    {nid}["{_label(res)}"]')
        if res.get("exposure") == "public":
            lines.append(f"    internet --> {nid}")
            public_nodes.append(nid)

    for edge in graph.get("edges", []):
        src = idmap.get(edge["from"])
        dst = idmap.get(edge["to"])
        if src and dst:
            lines.append(f'    {src} -->|{edge["relation"]}| {dst}')

    lines.append("    classDef ext fill:#eef,stroke:#557;")
    lines.append("    classDef public fill:#fee,stroke:#a33,stroke-width:2px;")
    if public_nodes:
        lines.append(f"    class {','.join(public_nodes)} public;")
    return "\n".join(lines)
