#!/usr/bin/env python3
"""Regenerate / expand the ATT&CK cloud corpus from a pinned MITRE STIX release.

The committed ``data/attack_cloud_corpus.json`` is the source of truth at runtime (no network
needed). This dev-time script lets you rebuild or widen it from the official MITRE ATT&CK STIX
bundle, filtered to cloud-relevant platforms — keeping the corpus a *pinned, reproducible*
snapshot (resolves the "ATT&CK ID drift" concern from Phase 3).

Usage:
    python scripts/build_attack_corpus.py --version 15.1 \
        --out src/iac_threatgen/data/attack_cloud_corpus.json

Requires network + the `openai`-provided `httpx` (already in requirements). It deliberately does
NOT run as part of the pipeline.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Official MITRE ATT&CK STIX data, pinned by tag. See https://github.com/mitre-attack/attack-stix-data
STIX_URL = (
    "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/"
    "master/enterprise-attack/enterprise-attack-{version}.json"
)
CLOUD_PLATFORMS = {"IaaS", "SaaS", "Identity Provider", "Office Suite", "Containers"}


def build(version: str) -> dict:
    import httpx  # provided transitively by openai

    url = STIX_URL.format(version=version)
    resp = httpx.get(url, timeout=60.0, follow_redirects=True)
    resp.raise_for_status()
    bundle = resp.json()

    techniques: list[dict] = []
    for obj in bundle.get("objects", []):
        if obj.get("type") != "attack-pattern":
            continue
        if obj.get("revoked") or obj.get("x_mitre_deprecated"):
            continue
        platforms = set(obj.get("x_mitre_platforms", []))
        if not (platforms & CLOUD_PLATFORMS):
            continue
        ext = next(
            (r for r in obj.get("external_references", []) if r.get("source_name") == "mitre-attack"),  # noqa: E501
            None,
        )
        if not ext:
            continue
        techniques.append(
            {
                "technique_id": ext["external_id"],
                "name": obj.get("name", ""),
                "tactics": [p["phase_name"] for p in obj.get("kill_chain_phases", [])],
                "platforms": sorted(platforms & CLOUD_PLATFORMS),
                "description": (obj.get("description", "") or "").strip().split("\n")[0],
                "url": ext.get("url", ""),
            }
        )
    techniques.sort(key=lambda t: t["technique_id"])
    return {
        "metadata": {
            "source": "MITRE ATT&CK Enterprise STIX",
            "attack_version": version,
            "note": "Generated by scripts/build_attack_corpus.py — pinned MITRE STIX release.",
            "license": "ATT&CK content © The MITRE Corporation, used per the ATT&CK Terms of Use.",
        },
        "techniques": techniques,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--version", required=True, help="ATT&CK release tag, e.g. 15.1")
    ap.add_argument(
        "--out", default="src/iac_threatgen/data/attack_cloud_corpus.json", type=Path
    )
    args = ap.parse_args()

    corpus = build(args.version)
    args.out.write_text(json.dumps(corpus, indent=2), encoding="utf-8")
    print(f"Wrote {len(corpus['techniques'])} techniques to {args.out} (ATT&CK {args.version}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
